language: java
jdk:
 - oraclejdk8
sudo: false
services:
- mysql
before_install:
- mysql -u root --password="" < webapp/database/travis.sql
install: true
script:
- cd webapp
- mvn clean verify

notifications:
email:
recipients:
- wu.x@husky.neu.edu
