language: java
jdk:
  - oraclejdk8
node_js: "6.12.3"
sudo: true
services:
  - mysql
before_install:
  - mysql -u root --password="" < webapp/database/travis.sql
  - npm install -g @angular/cli@latest
install: true
script:
  - cd webapp
  - mvn clean verify
  - cd src/main/resources/static
  - rm -rf node_modules
  - rm package-lock.json
  - npm install
  - ng build --prod --aot=false
deploy:
  on:
    branch: master
  provider: s3
  assess_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: asdf
  skip_cleanup: false

notifications:
  email:
  recipients:
  - wu.x@husky.neu.edu
