language: java
jdk:
  - oraclejdk8
node_js: "6.12.3"
sudo: true
services:
  - mysql
before_install:
  - mysql -u root --password="" < webapp/database/travis.sql
  - npm install -g @angular/cli@latest
install: true
script:
  - cd webapp
  - mvn clean package
  - cd target
  - ls -al
  - cd ..
  - cd ..
  - cd frontend
  - rm -rf node_modules
  - rm package-lock.json
  - npm install
  - ng build --prod --aot=false
  - cd ..
  - ls -al
after_success:
  - pwd
  - mkdir codedeploy_artifact
  - cd frontend
  - rm -rf node_modules
  - ls -al
  - cd ..
  - mv webapp/target/webapp-ROOT.war webapp/target/ROOT.war
  - zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip frontend/ webapp/target/ROOT.war *.sh *.yml
  - ls -al
  - pwd
  - cd codedeploy_artifact
  - ls -al
  - cd ..
  - pwd
  - ls -al
deploy:
  - provider: s3
    assess_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: code-deploy.csye6225-spring2018-wux.tld
    skip_cleanup: true
    on:
      branch: master
  - provider: codedeploy
    assess_key_id: $AWS_ACCESS_KEY_ID
    bucket: code-deploy.csye6225-spring2018-wux.tld
    bundle_type: zip
    key: csye6225-web-app-$TRAVIS_JOB_NUMBER.zip
    application: CodeDeployApplicationAssignment6CICD
    deployment_group: deploymentGroup
    region: us-east-1
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    wait-until-deployed: true
    skip_cleanup: true


notifications:
  email:
  recipients:
  - wu.x@husky.neu.edu
