language: java
jdk:
  - oraclejdk8
node_js: "6.12.3"
sudo: true
services:
  - mysql
before_install:
  - mysql -u root --password="" < webapp/database/travis.sql
install: true
script:
  - cd webapp
  - mvn clean verify
  - cd src/main/resources/static
  - npm install -g @angular/cli
  - npm install
  - ng build --prod

notifications:
  email:
  recipients:
  - wu.x@husky.neu.edu
