version: 0.0
os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./frontend/dist
    destination: /var/lib/tomcat8/webapps/ROOT
  - source: ./webapp/build/libs/ROOT.war
    destination: /var/lib/tomcat8/webapps
  - source: ./webapp/database/travis.sql
    destination: /var/lib/tomcat8/webapps

hooks:
  BeforeInstall:
   - location: ./beforeInstall.sh
     timeout: 180
     runas: ubuntu
  AfterInstall:
   - location: ./testDeploy.sh
     timeout: 180
     runas: ubuntu
  ApplicationStart:
   - location: ./applicationStart.sh
     runas: ubuntu
     timeout: 180
